"use client";
import dynamic from "next/dynamic";
export const GENERATED_DEMOS = {
  "mark": dynamic(() => import("./demos/generated/foundation").then(m => m.MarkDemo)),
  "section-tag": dynamic(() => import("./demos/generated/foundation").then(m => m.SectionTagDemo)),
  "rule": dynamic(() => import("./demos/generated/foundation").then(m => m.RuleDemo)),
  "badge": dynamic(() => import("./demos/generated/foundation").then(m => m.BadgeDemo)),
  "spinner": dynamic(() => import("./demos/generated/foundation").then(m => m.SpinnerDemo)),
  "frame": dynamic(() => import("./demos/generated/foundation").then(m => m.FrameDemo)),
  "slider": dynamic(() => import("./demos/generated/foundation").then(m => m.SliderDemo)),
  "tooltip": dynamic(() => import("./demos/generated/foundation").then(m => m.TooltipDemo)),
  "form-field": dynamic(() => import("./demos/generated/forms").then(m => m.FormFieldDemo)),
  "text-field": dynamic(() => import("./demos/generated/forms").then(m => m.TextFieldDemo)),
  "text-area": dynamic(() => import("./demos/generated/forms").then(m => m.TextAreaDemo)),
  "select-field": dynamic(() => import("./demos/generated/forms").then(m => m.SelectFieldDemo)),
  "checkbox": dynamic(() => import("./demos/generated/forms").then(m => m.CheckboxDemo)),
  "switch": dynamic(() => import("./demos/generated/forms").then(m => m.SwitchDemo)),
  "search-field": dynamic(() => import("./demos/generated/forms").then(m => m.SearchFieldDemo)),
  "password-field": dynamic(() => import("./demos/generated/forms").then(m => m.PasswordFieldDemo)),
  "radio-group": dynamic(() => import("./demos/generated/forms").then(m => m.RadioGroupDemo)),
  "segmented-control": dynamic(() => import("./demos/generated/forms").then(m => m.SegmentedControlDemo)),
  "number-field": dynamic(() => import("./demos/generated/forms").then(m => m.NumberFieldDemo)),
  "rating": dynamic(() => import("./demos/generated/forms").then(m => m.RatingDemo)),
  "color-picker": dynamic(() => import("./demos/generated/forms").then(m => m.ColorPickerDemo)),
  "tag-input": dynamic(() => import("./demos/generated/forms").then(m => m.TagInputDemo)),
  "file-dropzone": dynamic(() => import("./demos/generated/forms").then(m => m.FileDropzoneDemo)),
  "async-form": dynamic(() => import("./demos/generated/forms").then(m => m.AsyncFormDemo)),
  "status": dynamic(() => import("./demos/generated/status").then(m => m.StatusDemo)),
  "alert": dynamic(() => import("./demos/generated/status").then(m => m.AlertDemo)),
  "progress": dynamic(() => import("./demos/generated/status").then(m => m.ProgressDemo)),
  "meter": dynamic(() => import("./demos/generated/status").then(m => m.MeterDemo)),
  "skeleton": dynamic(() => import("./demos/generated/status").then(m => m.SkeletonDemo)),
  "empty-state": dynamic(() => import("./demos/generated/status").then(m => m.EmptyStateDemo)),
  "error-state": dynamic(() => import("./demos/generated/status").then(m => m.ErrorStateDemo)),
  "connection-status": dynamic(() => import("./demos/generated/status").then(m => m.ConnectionStatusDemo)),
  "save-indicator": dynamic(() => import("./demos/generated/status").then(m => m.SaveIndicatorDemo)),
  "async-boundary": dynamic(() => import("./demos/generated/status").then(m => m.AsyncBoundaryDemo)),
  "task-progress": dynamic(() => import("./demos/generated/status").then(m => m.TaskProgressDemo)),
  "async-button": dynamic(() => import("./demos/generated/status").then(m => m.AsyncButtonDemo)),
};
