import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { format } from "prettier";
import { CATALOG } from "../src/components/docs/catalog";
import {
  COMPONENTS,
  SYSTEMS,
  CATEGORIES,
} from "../src/components/docs/registry";

const checking = process.argv.includes("--check");
function output(path: string, value: string) {
  if (!checking) writeFileSync(path, value);
  else if (readFileSync(path, "utf8") !== value) {
    console.error(`Regenerate ${path}: bun run examples:sync`);
    process.exitCode = 1;
  }
}
async function typescript(path: string, value: string) {
  output(path, await format(value, { parser: "typescript" }));
}

// Compile the documented examples as live demos: copied usage cannot silently drift.
const overrides: Record<string, string> = {
  AsyncForm: `  return <AsyncForm onSubmit={async (data) => { localStorage.setItem("mizu-demo-name", String(data.get("name"))); }} successMessage="Saved on this device."><TextField label="Display name" name="name" required /><button type="submit" className="mizu-text-button">Save locally</button></AsyncForm>;`,
  EmptyState: `  const [created, setCreated] = useState(false);\n  return created ? <p>Your new draft is ready.</p> : <EmptyState title="No releases yet" action={<Button size="sm" onClick={() => setCreated(true)}>Create a release</Button>}>Your first release starts with a finished piece.</EmptyState>;`,
};
const families = new Map<string, typeof CATALOG>();
for (const entry of CATALOG)
  families.set(entry.category, [
    ...(families.get(entry.category) ?? []),
    entry,
  ]);
mkdirSync("src/components/docs/demos/generated", { recursive: true });
const demoLines: string[] = [];
for (const [family, entries] of families) {
  const imports = new Set<string>();
  const bodies = entries.map((entry) => {
    const match = entry.usage.match(/import \{ (.+) \} from "mizu-ui"/)!;
    match[1].split(",").forEach((name) => imports.add(name.trim()));
    const body =
      overrides[entry.name] ??
      entry.usage.slice(
        entry.usage.indexOf("export function Example() {") +
          "export function Example() {\n".length,
        -2,
      );
    demoLines.push(
      `  "${entry.slug}": dynamic(() => import("./demos/generated/${family.toLowerCase()}").then(m => m.${entry.name}Demo)),`,
    );
    return `export function ${entry.name}Demo() {\n${body}\n}`;
  });
  await typescript(
    `src/components/docs/demos/generated/${family.toLowerCase()}.tsx`,
    `"use client";\n// Generated from catalog usage by bun run examples:sync.\n${bodies.some((b) => b.includes("useState")) ? 'import { useState } from "react";\n' : ""}import { ${[...imports].join(", ")} } from "@/mizu";\n\n${bodies.join("\n\n")}\n`,
  );
}
await typescript(
  "src/components/docs/GeneratedDemos.tsx",
  `"use client";\nimport dynamic from "next/dynamic";\nexport const GENERATED_DEMOS = {\n${demoLines.join("\n")}\n};\n`,
);

const legacy = COMPONENTS.filter((entry) => !CATALOG.includes(entry));
const legacyImports = new Set<string>();
const legacyBodies = legacy.map((entry) => {
  for (const match of entry.usage.matchAll(/import \{ (.+) \} from "mizu-ui"/g))
    match[1].split(",").forEach((n) => legacyImports.add(n.trim()));
  return entry.usage
    .replace(/^import .*;\n?/gm, "")
    .trim()
    .replace(
      /export function (\w+)/g,
      (_, name: string) => `export function ${entry.name}Usage_${name}`,
    );
});
await typescript(
  "src/components/docs/demos/generated/legacy-examples.tsx",
  `"use client";\n// Compile the original copied examples too; these do not replace their interactive demos.\nimport { useState, type ReactNode } from "react";\nimport { ${[...legacyImports].join(", ")} } from "@/mizu";\n\n${legacyBodies.join("\n\n")}\n`,
);

const usage: Record<string, string> = {};
for (const entry of COMPONENTS)
  usage[entry.slug] = await format(entry.usage, { parser: "typescript" });
output("src/components/docs/usage.json", JSON.stringify(usage, null, 2) + "\n");

// The same inventory drives discovery, source routes and the release count.
const inventory = [
  "# Component inventory",
  "",
  `Generated by bun run examples:sync. ${SYSTEMS.length} systems across ${CATEGORIES.length} families. Compound parts, providers and aliases are counted with their parent; the primitives overview is excluded.`,
  "",
  "Every entry has a preview, compiled usage, property notes, accessibility and motion guidance, and an inspectable source route. Passing the catalog check verifies those records, not exhaustive browser or assistive-technology coverage.",
  "",
];
for (const family of CATEGORIES) {
  const entries = SYSTEMS.filter((e) => e.category === family);
  inventory.push(
    `## ${family} (${entries.length})`,
    "",
    "| System | Purpose | Source |",
    "| --- | --- | --- |",
  );
  for (const e of entries)
    inventory.push(
      `| **${e.name}** | ${e.tagline.replace(/\|/g, "\\|")} | [${e.source}](../packages/mizu/src/${e.source}) |`,
    );
  inventory.push("");
}
output("docs/COMPONENTS.md", inventory.join("\n"));
