import { define as d, prop as p } from "./define";
export const CONTENT = [
  d(
    "Avatar",
    "Content",
    "content/Media.tsx",
    "Identity at a glance, with initials that survive a missing image.",
    '  return <div style={{display:"flex",gap:12,alignItems:"center"}}><Avatar name="Mizu Workshop" /><Avatar name="Aya Mori" size={60} /><span className="mizu-field-hint">A small team, clearly named.</span></div>;',
    [
      p("name", "string", "Accessible identity and fallback initials."),
      p(
        "src / size",
        "string / number",
        "Optional image and diameter in pixels.",
        "44",
      ),
    ],
    "One named image; redundant initials are hidden. Failed images fall back to initials.",
    "Static identity.",
  ),
  d(
    "Kbd",
    "Content",
    "content/Typography.tsx",
    "Keyboard hints set apart from the surrounding sentence.",
    "  return <p>Press <Kbd>⌘</Kbd> + <Kbd>K</Kbd> to open your command palette.</p>;",
    [
      p("children", "ReactNode", "Key name or chord."),
      p("...props", "HTMLAttributes", "Native kbd attributes."),
    ],
    "Native kbd semantics. This displays a hint; keyboard handlers belong to the associated feature.",
    "Static typographic cue.",
  ),
  d(
    "CodeBlock",
    "Content",
    "content/Typography.tsx",
    "Selectable source with a real copy action and room for long lines.",
    '  return <CodeBlock filename="app.tsx" language="tsx" code={"import { Button } from \\\"mizu-ui\\\";\\n\\n<Button>Make something</Button>"} />;',
    [
      p("code", "string", "Complete source text."),
      p(
        "language / filename",
        "string",
        "Caption metadata; no syntax parser is loaded.",
      ),
    ],
    "Focus the preformatted region to scroll. CopyButton reports clipboard failure. Content is React-escaped, never injected HTML.",
    "Static source display.",
  ),
  d(
    "Quote",
    "Content",
    "content/Typography.tsx",
    "A serif voice in the margin, with an honest attribution.",
    '  return <Quote author="Mizu design note">The interface should make the next action feel obvious.</Quote>;',
    [
      p("children", "ReactNode", "Quoted content."),
      p("author / cite", "string", "Attribution and optional source URL."),
    ],
    "Native blockquote and figcaption. A supplied citation becomes an actual link.",
    "Static editorial content.",
  ),
  d(
    "Prose",
    "Content",
    "content/Typography.tsx",
    "A readable measure for long-form documents inside an interface.",
    '  return <Prose><h2>Interfaces are instruments.</h2><p>They give people a way to observe, choose and change something. A clear reading rhythm keeps those decisions in focus.</p><ul><li>Keep labels visible.</li><li>Explain the next action.</li></ul><p>Begin with the <a href="/components/getting-started">installation guide</a>.</p></Prose>;',
    [
      p(
        "children",
        "ReactNode",
        "Semantic headings, paragraphs, lists and links.",
      ),
      p("...props", "HTMLAttributes", "Native wrapper attributes."),
    ],
    "Readability is CSS only. The author supplies correct heading levels and meaningful link text.",
    "Static reading layout.",
  ),
  d(
    "ImageFigure",
    "Content",
    "content/Media.tsx",
    "Responsive imagery with a caption and a visible failure state.",
    '  return <ImageFigure src="/images/field.svg" alt="Warm diamonds arranged on a dark measurement field" caption="Field study 01 — a repeatable spacing rhythm." width={720} height={360} />;',
    [
      p(
        "src / alt",
        "string",
        "Resource URL and meaningful image description.",
      ),
      p("caption", "ReactNode", "Optional visible context."),
      p(
        "...props",
        "ImgHTMLAttributes",
        "Native image attributes, including dimensions and srcSet.",
      ),
    ],
    "Native figure/image/caption; lazy by default. Supply dimensions to prevent shifts. Failed images retain the description.",
    "Static media.",
  ),
  d(
    "MediaPlayer",
    "Content",
    "content/Media.tsx",
    "Playback handed to the browser's accessible controls.",
    '  return <MediaPlayer kind="audio" label="A four-second calibration tone" src="/audio/calibration.wav" preload="metadata" />;',
    [
      p("kind", '"audio" | "video"', "Native media element.", '"video"'),
      p("label", "string", "Figure and player name."),
      p(
        "...props / children",
        "VideoHTMLAttributes / ReactNode",
        "Native source, poster, tracks, events; children may include caption tracks.",
      ),
    ],
    "Native controls support keyboard and touch. Provide captions/transcripts for speech and video. Autoplay is opt-in through native props.",
    "Playback follows user intent; no synthetic timer.",
  ),
  d(
    "LinkCard",
    "Content",
    "content/Typography.tsx",
    "A destination with enough context to decide whether to follow it.",
    '  return <LinkCard href="/components/getting-started" eyebrow="START HERE" title="Build with Mizu" description="Install the package, bring the styles and compose your first interface." />;',
    [
      p("href / title", "string", "Real destination and visible link title."),
      p("description / eyebrow", "string", "Supporting context."),
      p("...props", "AnchorHTMLAttributes", "Native link behavior."),
    ],
    "A single native anchor, no nested interactive elements. Open-in-new-tab behavior remains browser-owned.",
  ),
  d(
    "FileCard",
    "Content",
    "content/Typography.tsx",
    "A downloadable resource with a legible name and size.",
    '  return <FileCard href="/api/source/button" name="Button.tsx" type="TypeScript source" />;',
    [
      p("href / name", "string", "Resource URL and filename."),
      p("size", "number", "Optional actual byte count."),
      p(
        "type / download",
        "string / boolean",
        "File descriptor and download preference.",
        "true",
      ),
    ],
    "Native download anchor, readable metadata. Cross-origin servers control whether download is honored; this component never invents file size.",
    "Static resource link.",
  ),
  d(
    "Checklist",
    "Content",
    "content/Checklist.tsx",
    "Complete a set of real tasks and see how much remains.",
    '  const [items,setItems] = useState([{id:"types",label:"Check types",checked:true},{id:"browser",label:"Review in the browser",description:"Include a narrow screen and keyboard navigation.",checked:false},{id:"package",label:"Install the tarball",checked:false}]);\n  return <Checklist label="Release checks" items={items} onChange={(id,checked)=>setItems(items.map(i=>i.id===id ? {...i,checked} : i))} />;',
    [
      p(
        "items",
        "ChecklistItem[]",
        "Stable id, label, description, checked and disabled.",
      ),
      p(
        "onChange",
        "(id: string, checked: boolean) => void",
        "Persist or update each task.",
      ),
      p("label", "string", "Checklist legend."),
    ],
    "Native fieldset/checkboxes with linked descriptions. Count is derived from supplied state; no automatic completion.",
    "State changes remain stable; no layout travel.",
  ),
];
