import { define as d, prop as p } from "./define";
export const DATA = [
  d(
    "DataTable",
    "Data",
    "data/DataTable.tsx",
    "A sortable, typed table that keeps native table semantics and nulls in their place.",
    '  const rows = [{id:"a",name:"WaveText",size:4.2},{id:"b",name:"Button",size:1.8},{id:"c",name:"Signal",size:3.1}];\n  return <DataTable label="Package modules" rows={rows} getRowId={r => r.id} columns={[{id:"name",header:"Name",render:r => r.name,sortValue:r => r.name},{id:"size",header:"Size (KiB)",render:r => r.size,sortValue:r => r.size,align:"right"}]} />;',
    [
      p("rows", "T[]", "Your rows; pagination and fetching remain outside."),
      p(
        "columns",
        "DataColumn<T>[]",
        "Stable id, header, render, optional sortValue and alignment.",
      ),
      p("getRowId", "(row: T) => string", "Stable row identity."),
      p(
        "label / loading / empty",
        "string / boolean / ReactNode",
        "Caption, busy state and empty content.",
      ),
    ],
    "Native caption, headers and cells. Sort controls expose aria-sort. Overflow is focusable; null sort values stay last in either direction.",
  ),
  d(
    "DescriptionList",
    "Data",
    "data/Records.tsx",
    "Aligned names and values with the semantics of a description list.",
    '  return <DescriptionList items={[{label:"Package",value:"mizu-ui"},{label:"License",value:"MIT"},{label:"Format",value:"ES modules"}]} />;',
    [
      p(
        "items",
        "{label: string; value: ReactNode}[]",
        "Terms and descriptions.",
      ),
    ],
    "Native dl/dt/dd relationships. Values can contain links or controls.",
    "Static, reflowing layout.",
  ),
  d(
    "Stat",
    "Data",
    "data/Records.tsx",
    "A metric with context: direction and favorability are separate decisions.",
    '  return <Stat label="Build duration" value="1.2s" change={{value:"18% faster",direction:"down",favorable:true}} detail="Compared with the previous local run." />;',
    [
      p("label / value", "string / ReactNode", "Metric name and reading."),
      p(
        "change",
        "{value, direction, favorable?}",
        "Text, trend and whether that trend is desirable.",
      ),
      p("detail", "string", "Supporting context."),
    ],
    "The direction is readable and announced independently of color. A falling value is not automatically bad.",
    "Static measurement.",
  ),
  d(
    "BarChart",
    "Data",
    "data/Charts.tsx",
    "Readable, labelled comparisons without a charting dependency.",
    '  return <BarChart label="Components by family" data={[{label:"Forms",value:16},{label:"Status",value:12},{label:"Motion",value:5}]} />;',
    [
      p("data", "ChartPoint[]", "Labels and numeric readings."),
      p("format", "(value: number) => string", "Visible units."),
      p("label", "string", "Figure caption."),
    ],
    "All labels and readings are real list text. Negative values keep their sign and use a distinct treatment; bars compare absolute magnitudes.",
  ),
  d(
    "Sparkline",
    "Data",
    "data/Charts.tsx",
    "A compact history trace with the underlying readings in its accessible name.",
    '  return <Sparkline label="Weekly build duration in seconds" values={[4,3,3.6,2.2,2.8,1.5,1.2]} />;',
    [
      p(
        "values",
        "number[]",
        "Sequential readings; non-finite values are omitted.",
      ),
      p("label", "string", "Describe the quantity and units."),
    ],
    "SVG has a unique title with the full readings. Use a table for large datasets; this is a compact trend.",
    "Static SVG, no background loop.",
  ),
  d(
    "Heatmap",
    "Data",
    "data/Charts.tsx",
    "A daily activity field with every date and reading available as text.",
    '  const data = Array.from({length:70}, (_,i) => ({date:`2026-${String(Math.floor(i/28)+7).padStart(2,"0")}-${String(i%28+1).padStart(2,"0")}`,value:(i*7)%11}));\n  return <Heatmap label="Workshop activity" data={data} />;',
    [
      p(
        "data",
        "{date: string; value: number}[]",
        "Days in chronological order; supply missing days as zero.",
      ),
      p("label", "string", "Figure caption."),
    ],
    "Each square includes its date/value as screen-reader text. The full grid scrolls on narrow screens; color is never the only source of data.",
    "Static CSS grid.",
  ),
  d(
    "Timeline",
    "Data",
    "data/Records.tsx",
    "Events connected by a fine thread, with the present kept distinct.",
    '  return <Timeline items={[{id:"a",title:"Foundations repaired",time:"Monday",state:"complete",body:"Keyboard and motion contracts checked."},{id:"b",title:"Package validated",time:"Tuesday",state:"current",body:"Fresh tarball installation passed."},{id:"c",title:"Release review",time:"Wednesday",state:"upcoming"}]} />;',
    [
      p(
        "items",
        "TimelineEvent[]",
        "Stable id, title, time, optional dateTime, body and state.",
      ),
      p("label", "string", "List name.", '"Timeline"'),
    ],
    "Ordered list and time elements preserve chronology. State is a visual aid, so include state information in the event content when essential.",
    "Static connective geometry.",
  ),
  d(
    "ActivityFeed",
    "Data",
    "data/Inspection.tsx",
    "Filter a real event stream by its event type without losing chronological context.",
    '  return <ActivityFeed items={[{id:"a",actor:"You",action:"created WaveText",time:"10:24",type:"Created"},{id:"b",actor:"Mizu",action:"validated the package",time:"10:31",type:"Validated"},{id:"c",actor:"You",action:"created Signal",time:"11:02",type:"Created"}]} />;',
    [
      p(
        "items",
        "Activity[]",
        "Stable event id, actor, action, time and optional type/dateTime.",
      ),
      p("label", "string", "Feed and filter name."),
    ],
    "Events are an ordered list. A labelled native select filters event types. Empty views remain explained.",
  ),
  d(
    "DiffView",
    "Data",
    "data/Inspection.tsx",
    "Two text versions, aligned by line, with changes made visible.",
    '  return <DiffView before={"surface: ink\\nfocus: muted\\nmotion: always"} after={"surface: ink\\nfocus: accent\\nmotion: reduced-safe"} />;',
    [
      p("before / after", "string", "The two complete texts."),
      p("beforeLabel / afterLabel", "string", "Version labels."),
    ],
    "Each version is a named section with selectable code. This is an aligned-line comparison, not an edit-distance engine; insertions may mark following lines changed.",
    "Static version comparison.",
  ),
  d(
    "DataInspector",
    "Data",
    "data/Inspection.tsx",
    "Open a payload, follow its structure and copy the JSON without a developer-tools panel.",
    '  return <DataInspector label="Release payload" value={{name:"mizu-ui",version:"0.2.0",checks:{types:true,lint:true},files:["styles.css","fonts.css"]}} />;',
    [
      p("value", "unknown", "A JSON-like object, array or scalar."),
      p("label", "string", "Section name.", '"Data"'),
    ],
    "Native disclosure controls. Circular objects are marked; copy is omitted when serialization fails. Depth is capped at eight and siblings at 200.",
    "Native disclosure; no observers.",
  ),
  d(
    "TreeView",
    "Data",
    "data/Inspection.tsx",
    "Browse a hierarchy with native disclosure and an optional selected leaf.",
    '  const [selected,setSelected] = useState("button");\n  return <TreeView selected={selected} onSelect={setSelected} nodes={[{id:"ui",label:"Foundation",children:[{id:"button",label:"Button.tsx"},{id:"badge",label:"Badge.tsx"}]},{id:"styles",label:"styles.css"}]} />;',
    [
      p("nodes", "TreeNode[]", "Stable id, label and optional children."),
      p("selected / onSelect", "string / function", "Optional leaf selection."),
    ],
    "Nested lists and native details; not an ARIA tree widget. Tab and Enter operate disclosures and leaf buttons. Depth is bounded at 16.",
    "Native disclosure.",
  ),
  d(
    "ComparisonTable",
    "Data",
    "data/Records.tsx",
    "A feature matrix whose rows and columns stay connected to their meaning.",
    '  return <ComparisonTable label="Release formats" columns={["Source","Package"]} rows={[{label:"Typed declarations",values:[false,true]},{label:"Inspectable source",values:[true,true]},{label:"Setup",values:["Copy files","Install once"]}]} />;',
    [
      p("columns", "string[]", "Column headings."),
      p(
        "rows",
        "{label: string; values: (string | boolean)[]}[]",
        "Feature rows aligned to the columns.",
      ),
      p("label", "string", "Table caption."),
    ],
    "Row/column headers and caption are native. Boolean values use Included/Not included text; missing cells display a dash.",
    "Static, scrollable table.",
  ),
];
