import { define as d, prop as p } from "./define";
export const FORMS = [
  d("FormField", "Forms", "forms/Fields.tsx", "A label, hint and error linked to a single control without manual IDs.", '  return <FormField label="Project" hint="A name people can find"><input className="mizu-input" /></FormField>;', [p("label", "string", "Visible accessible label."), p("hint / error", "ReactNode / string", "Description and validation feedback."), p("children", "ReactElement", "One control that accepts id and ARIA attributes.")], "The label, hint and error are linked by unique IDs. Errors are announced. Use one native control as the child."),
  d("TextField", "Forms", "forms/Fields.tsx", "A precise, labelled input with native validation and clear error feedback.", '  return <TextField label="Project name" name="project" required placeholder="Untitled project" hint="Visible to your collaborators." />;', [p("label", "string", "Visible input label."), p("hint / error", "ReactNode / string", "Linked help and validation."), p("...input", "InputHTMLAttributes", "Native value, onChange, type, required, ref and validation.")], "A real labelled input; descriptions and errors use aria-describedby. Supports native input types and autocomplete."),
  d("TextArea", "Forms", "forms/Fields.tsx", "Long-form input with resizable room for thoughts, labels and validation.", '  return <TextArea label="Release notes" name="notes" rows={4} placeholder="What changed?" />;', [p("label", "string", "Accessible label."), p("rows", "number", "Initial text rows.", "4"), p("...textarea", "TextareaHTMLAttributes", "Native input events, limits and ref.")], "Native textarea with a linked label, hint and error. Users can resize vertically."),
  d("SelectField", "Forms", "forms/Fields.tsx", "Native selection that retains the platform's keyboard and touch behavior.", '  return <SelectField label="Visibility" defaultValue="private"><option value="private">Private</option><option value="public">Public</option></SelectField>;', [p("label", "string", "Accessible select label."), p("children", "option[]", "Native option elements."), p("...select", "SelectHTMLAttributes", "Native value, multiple, events and ref.")], "Uses the platform select menu. Arrow keys, type-ahead and mobile selection are native."),
  d("Checkbox", "Forms", "forms/Fields.tsx", "A generous check target with a secondary description and native form submission.", '  return <Checkbox label="Include source maps" hint="Useful when debugging production." name="sourcemaps" defaultChecked />;', [p("label", "ReactNode", "Clickable label."), p("hint", "string", "Linked secondary description."), p("...input", "InputHTMLAttributes", "Native checked, defaultChecked, events, name and ref.")], "The full label is clickable. Native checkbox handles Space, focus and checked state."),
  d("Switch", "Forms", "forms/Fields.tsx", "A tactile binary setting whose thumb tracks the state.", '  return <Switch label="Email notifications" name="notifications" defaultChecked />;', [p("label", "string", "Setting name."), p("...input", "InputHTMLAttributes", "Native checked/defaultChecked, disabled, onChange and ref.")], "A native checkbox with role=switch. Space toggles; visible focus follows the thumb."),
  d("SearchField", "Forms", "forms/Fields.tsx", "Search with a clear action that belongs to the input.", '  const [query, setQuery] = useState("");\n  return <SearchField value={query} onValueChange={setQuery} label="Find a component" />;', [p("value", "string", "Controlled query."), p("onValueChange", "(value: string) => void", "Typing and clear events."), p("label", "string", "Input label.", '"Search"')], "Uses input type=search and a separately named clear button. Does not impose a search algorithm."),
  d("PasswordField", "Forms", "forms/Fields.tsx", "A revealable secret with explicit visibility feedback.", '  return <PasswordField label="Password" name="password" autoComplete="new-password" />;', [p("label", "string", "Accessible label."), p("...input", "InputHTMLAttributes", "Native value, autocomplete and ref.")], "The reveal button reports aria-pressed and keeps its name synchronized. Does not copy or store secrets."),
  d("RadioGroup", "Forms", "forms/Selection.tsx", "Mutually exclusive choices with room to explain what each choice means.", '  const [value, setValue] = useState("local");\n  return <RadioGroup label="Storage" value={value} onValueChange={setValue} options={[{value:"local",label:"Local",description:"On this device"},{value:"cloud",label:"Cloud",description:"Across devices"}]} />;', [p("options", "Choice[]", "Value, label, optional description and disabled."), p("value / onValueChange", "string / function", "Controlled selection."), p("name", "string", "Form field name. Unique by default.")], "Fieldset/legend and native radios supply group semantics and arrow-key behavior."),
  d("SegmentedControl", "Forms", "forms/Selection.tsx", "A compact selection rail for density, view and other immediate choices.", '  const [value, setValue] = useState("week");\n  return <SegmentedControl label="Period" value={value} onValueChange={setValue} options={[{value:"day",label:"Day"},{value:"week",label:"Week"},{value:"month",label:"Month"}]} />;', [p("options", "Choice[]", "Visible choices and disabled states."), p("value / onValueChange", "string / function", "Controlled selected segment.")], "Native radios supply keyboard navigation. It selects a value; use Tabs for associated content panels."),
  d("NumberField", "Forms", "forms/Selection.tsx", "A bounded numeric stepper that survives decimals and repeated actions.", '  const [value, setValue] = useState(3);\n  return <NumberField label="Seats" value={value} onValueChange={setValue} min={1} max={12} />;', [p("value / onValueChange", "number / function", "Controlled numeric value."), p("min / max", "number", "Inclusive bounds."), p("step", "number", "Increment size.", "1")], "A labelled native number input plus named increase/decrease buttons. Bounds disable impossible actions."),
  d("Rating", "Forms", "forms/Selection.tsx", "A star rating you can choose with a mouse, touch or arrow keys.", '  const [value, setValue] = useState(3);\n  return <Rating label="How useful was this?" value={value} onValueChange={setValue} />;', [p("value / onValueChange", "number / function", "Controlled selected score."), p("max", "number", "One to ten stars.", "5")], "Native radio choices announce each score and support arrow keys. Decoration is hidden from readers."),
  d("ColorPicker", "Forms", "forms/Selection.tsx", "Named swatches and a native custom-color dialog, with the hex value always visible.", '  const [value, setValue] = useState("#ff4d1c");\n  return <ColorPicker label="Signal color" value={value} onValueChange={setValue} />;', [p("value / onValueChange", "string / function", "Six-digit hex color and callback."), p("swatches", "string[]", "Optional hex choices.")], "Swatches have color names/values and pressed state; a labelled native color input supplies custom selection."),
  d("TagInput", "Forms", "forms/TagInput.tsx", "Add, remove and deduplicate tags without losing the keyboard path.", '  const [value, setValue] = useState(["interface", "motion"]);\n  return <TagInput label="Topics" value={value} onValueChange={setValue} />;', [p("value / onValueChange", "string[] / function", "Controlled tag list."), p("maxTags", "number", "Maximum accepted tags.", "12")], "Enter/comma adds, Backspace removes the last tag. Each remove button is named; errors are announced and focus returns to the input."),
  d("FileDropzone", "Forms", "forms/FileDropzone.tsx", "Start a file upload by dropping or browsing, with size and type validation on both paths.", '  const [files, setFiles] = useState<File[]>([]);\n  return <><FileDropzone label="Attach artwork" accept="image/*,.svg" multiple onFilesChange={setFiles} /><p>{files.map(f => f.name).join(", ")}</p></>;', [p("onFilesChange", "(files: File[]) => void", "Receives validated files; upload remains your responsibility."), p("accept", "string", "Comma-separated extensions or MIME patterns."), p("maxSize", "number", "Bytes per file.", "10485760"), p("multiple", "boolean", "Allow multiple files.", "false")], "Keyboard users open the native file dialog with the browse button. Validation errors name the rejected files. Client checks do not replace server validation."),
  d("AsyncForm", "Forms", "forms/AsyncForm.tsx", "A form that follows the save promise and preserves input when a save fails.", '  return <AsyncForm onSubmit={async (data, signal) => { const response = await fetch("/api/settings", {method:"POST",body:data,signal}); if (!response.ok) throw new Error("Could not save settings."); }}><TextField label="Display name" name="name" required /><button type="submit" className="mizu-text-button">Save settings</button></AsyncForm>;', [p("onSubmit", "(data: FormData, signal: AbortSignal) => Promise<void>", "Native validity runs before submission. Signal aborts on unmount."), p("successMessage", "string", "Successful save feedback.", '"Saved."')], "Uses native form validation and disables the fieldset while pending. Errors are live; fields stay intact for correction.", "Pending state follows a real promise, never a simulated timeout.", "AsyncForm, TextField"),
];
