import { define as d, prop as p } from "./define";
export const FOUNDATION = [
  d(
    "Mark",
    "Foundation",
    "ui/Mark.tsx",
    "The diamond: a small marker for a state or position.",
    '  return <div style={{display:"flex",gap:24}}><Mark size={8} /><Mark size={12} tone="paper" /></div>;',
    [
      p("size", "number", "Diamond side in pixels.", "6"),
      p(
        "tone",
        '"accent" | "paper" | "muted" | "line"',
        "Token color.",
        '"accent"',
      ),
    ],
    "Decorative and hidden from assistive technology. Pair it with visible state text.",
    "Static geometry.",
  ),
  d(
    "SectionTag",
    "Foundation",
    "ui/SectionTag.tsx",
    "Compact structural text with an optional diamond marker.",
    '  return <SectionTag tone="accent">Interface craft</SectionTag>;',
    [
      p(
        "tone",
        '"muted" | "faint" | "paper" | "accent"',
        "Label color.",
        '"muted"',
      ),
      p("diamond", "boolean", "Show the marker.", "true"),
    ],
    "Readable paragraph text; use a heading element for a section title.",
    "Static text.",
  ),
  d(
    "Rule",
    "Foundation",
    "ui/Rule.tsx",
    "A hairline separator with a meaningful optional label.",
    '  return <Rule label="Next chapter" />;',
    [
      p("label", "string", "Optional visible separator text."),
      p("node", "boolean", "Show the diamond.", "true"),
      p("tone", '"line" | "line-bright" | "accent"', "Line color.", '"line"'),
    ],
    "A horizontal separator. The label is also exposed as its accessible name.",
    "Static geometry.",
  ),
  d(
    "Badge",
    "Foundation",
    "ui/Badge.tsx",
    "A compact, bordered label for metadata and status.",
    '  return <div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Badge tone="accent">New</Badge><Badge tone="paper">Stable</Badge><Badge>Draft</Badge></div>;',
    [
      p(
        "tone",
        '"paper" | "muted" | "accent" | "line"',
        "Label treatment.",
        '"muted"',
      ),
      p("diamond", "boolean", "Show the decorative marker.", "true"),
    ],
    "State remains visible text. Add a live region only when the status changes dynamically.",
    "Static text.",
  ),
  d(
    "Spinner",
    "Foundation",
    "ui/Spinner.tsx",
    "A rotating diamond with a clear loading announcement.",
    '  return <Spinner label="Loading artwork" size={18} />;',
    [
      p("size", "number", "Side in pixels.", "14"),
      p("label", "string", "Accessible loading name.", '"Loading"'),
      p("tone", '"accent" | "paper" | "muted"', "Color token.", '"accent"'),
    ],
    "A labelled status; reduced motion stops rotation.",
    "Linear rotation; static under reduced motion.",
  ),
  d(
    "Frame",
    "Foundation",
    "ui/Frame.tsx",
    "Crop marks that frame media without competing with it.",
    '  return <Frame label="Artwork"><div style={{padding:40,textAlign:"center"}}>A place for your work</div></Frame>;',
    [
      p("label", "string", "Figure caption."),
      p("tone", '"line" | "line-bright"', "Border contrast.", '"line"'),
    ],
    "Uses figure/figcaption semantics. Content provides its own alternative text.",
    "Static framing.",
  ),
  d(
    "Slider",
    "Foundation",
    "ui/Slider.tsx",
    "A diamond-thumb range with an always-readable value.",
    '  const [value, setValue] = useState(40);\n  return <Slider label="Density" value={value} min={0} max={100} onChange={setValue} />;',
    [
      p("label", "string", "Visible range label."),
      p("value / onChange", "number / function", "Controlled numeric value."),
      p("min / max / step", "number", "Range and step size."),
    ],
    "Labelled native range: keyboard arrows, Home/End and touch behavior are supplied by the browser.",
    "Thumb responds to pointer state.",
  ),
  d(
    "Tooltip",
    "Foundation",
    "ui/Tooltip.tsx",
    "A small, linked explanation that works with focus and can be dismissed.",
    '  return <Tooltip label="Keep your changes"><Button size="sm" variant="ghost">Save draft</Button></Tooltip>;',
    [
      p("label", "string", "Description linked to the control."),
      p("children", "ReactElement", "One element accepting aria-describedby."),
      p("side", '"top" | "bottom"', "Position.", '"top"'),
    ],
    "Shown on hover/focus and dismissed with Escape. Use a focusable control as the child. Avoid long or essential content.",
    "Short CSS transition; reduced motion removes travel.",
    "Tooltip, Button",
  ),
];
