import { define as d, prop as p } from "./define";
export const LAYOUT = [
  d(
    "Stack",
    "Layout",
    "layout/Layout.tsx",
    "A single-axis layout that wraps when the task calls for it.",
    '  return <Stack direction="row" wrap gap={12}><Badge>React</Badge><Badge>TypeScript</Badge><Badge>Native CSS</Badge></Stack>;',
    [
      p("direction", '"row" | "column"', "Main axis.", '"column"'),
      p(
        "gap / align / wrap",
        "number / CSS alignItems / boolean",
        "Spacing, cross-axis alignment and wrapping.",
      ),
      p(
        "...props",
        "HTMLAttributes",
        "Native div props; style can override defaults.",
      ),
    ],
    "No synthetic semantics. Use children with meaningful document structure.",
    "Native flex layout.",
    "Stack, Badge",
  ),
  d(
    "Grid",
    "Layout",
    "layout/Layout.tsx",
    "Responsive columns that make room for the content without breakpoint bookkeeping.",
    '  return <Grid minWidth={160} gap={24}><Stat label="Forms" value="16" /><Stat label="Status" value="12" /><Stat label="Data" value="12" /></Grid>;',
    [
      p(
        "minWidth / gap",
        "number",
        "Minimum column width and gap in pixels.",
        "220 / 24",
      ),
      p("...props", "HTMLAttributes", "Native div attributes."),
    ],
    "Native grid automatically collapses within its container. DOM reading order remains intact.",
    "CSS layout, no resize observer.",
    "Grid, Stat",
  ),
  d(
    "SplitPane",
    "Layout",
    "layout/SplitPane.tsx",
    "Give two working regions the space they need, with a real resizable boundary.",
    '  const [value,setValue] = useState(45);\n  return <SplitPane value={value} onValueChange={setValue} first={<div><h3>Source</h3><p className="mizu-field-hint">Drag the divider or focus it and use the arrow keys.</p></div>} second={<div><h3>Preview</h3><p className="mizu-field-hint">This panel receives {100-value}% of the available space.</p></div>} />;',
    [
      p("first / second", "ReactNode", "Two independent panels."),
      p(
        "value / onValueChange",
        "number / function",
        "Controlled percentage given to the first panel.",
      ),
      p(
        "min / max / label",
        "number / number / string",
        "Bounds and separator name.",
        "15 / 85",
      ),
    ],
    "Focusable separator with orientation, controls and current/min/max values. Arrow keys move 1%, Shift moves 10%; Home/End reach bounds. Pointer capture supports touch.",
    "Direct manipulation, no spring lag.",
  ),
  d(
    "AspectRatio",
    "Layout",
    "layout/Layout.tsx",
    "Reserve media space before it arrives, keeping the surrounding reading rhythm steady.",
    '  return <AspectRatio ratio={2}><img src="/images/field.svg" alt="A diamond measurement field" /></AspectRatio>;',
    [
      p("ratio", "number", "Width divided by height.", "16 / 9"),
      p(
        "children / ...props",
        "ReactNode / HTMLAttributes",
        "Native wrapper and media.",
      ),
    ],
    "CSS aspect-ratio reserves space; invalid ratios fall back to a square. Content retains its own accessibility.",
    "Static geometry.",
  ),
  d(
    "ScrollArea",
    "Layout",
    "layout/Layout.tsx",
    "A bounded reading region that keyboard users can enter and scroll.",
    '  return <ScrollArea label="Release notes" maxHeight={180}><Prose>{Array.from({length:8},(_,i)=><p key={i}>Entry {i+1}. Each component keeps its own behavior, source and usage example available.</p>)}</Prose></ScrollArea>;',
    [
      p("label", "string", "Region name."),
      p("maxHeight", "number | string", "Height limit.", "300"),
      p("...props", "HTMLAttributes", "Native div attributes."),
    ],
    "Named region is keyboard-focusable. Native scrolling, overscroll containment and platform scrollbars.",
    "Native scroll; no smoothing loop.",
    "ScrollArea, Prose",
  ),
  d(
    "AppShell",
    "Layout",
    "layout/Layout.tsx",
    "Named working regions and a skip link, composed around the product's real content.",
    '  return <AppShell mainTag="section" mainId="shell-demo-content" header={<strong>Workshop</strong>} sidebar={<SideNav currentPath="/components" groups={[{label:"Explore",items:[{label:"Collection",href:"/components"},{label:"Lab",href:"/lab"}]}]} />} footer={<span className="mizu-field-hint">All changes stay on this device.</span>}><h3>Your workspace</h3><p className="mizu-field-hint">A shell gives content a place; it does not decide the product for you.</p></AppShell>;',
    [
      p(
        "header / sidebar / footer / children",
        "ReactNode",
        "Composed regions.",
      ),
      p("mainId", "string", "Unique skip-link destination.", '"mizu-main"'),
      p(
        "mainTag",
        '"main" | "section"',
        "Use section when embedding in an existing main landmark.",
        '"main"',
      ),
    ],
    "Native landmarks and a visible-on-focus skip link. Supply a unique mainId per shell. Sidebar stacks on small screens.",
    "CSS reflow, no entrance animation.",
    "AppShell, SideNav",
  ),
];
