import { define as d, prop as p } from "./define";
export const STATUS = [
  d("Status", "Status", "status/Feedback.tsx", "A quiet diamond and a readable state, never color alone.", '  return <Status tone="success">Ready to publish</Status>;', [p("tone", '"neutral" | "success" | "warning" | "error"', "State color.", '"neutral"'), p("children", "ReactNode", "Readable status text.")], "Status text carries the meaning; the decorative diamond is hidden. Add role=status only for live updates."),
  d("Alert", "Status", "status/Feedback.tsx", "Contextual feedback with a title, explanation and a place to recover.", '  return <Alert title="Your draft is safe" tone="success">Saved locally. Publish when you are ready.</Alert>;', [p("title", "string", "Short feedback heading."), p("tone", "StatusTone", "Feedback severity."), p("action", "ReactNode", "Optional recovery control.")], "Error messages use role=alert; other feedback uses role=status. Write specific recovery instructions."),
  d("Progress", "Status", "status/Feedback.tsx", "Determinate or indeterminate progress, measured on a hairline track.", '  const [value, setValue] = useState(42);\n  return <><Progress label="Processing artwork" value={value} /><input type="range" aria-label="Demo progress" value={value} onChange={e => setValue(Number(e.target.value))} /></>;', [p("value", "number | undefined", "Omit for indeterminate progress."), p("max", "number", "Completion value.", "100"), p("label / showValue", "string / boolean", "Accessible label and visible percentage.")], "Native progress announces its value. Omitted value represents an unknown completion amount."),
  d("Meter", "Status", "status/Feedback.tsx", "A bounded measurement that distinguishes a reading from task completion.", '  return <Meter label="Storage used" value={68} low={30} high={85} optimum={20} format={v => `${v} GB of 100 GB`} />;', [p("value / min / max", "number", "Current reading and limits."), p("low / high / optimum", "number", "Native measurement thresholds."), p("format", "(value: number) => string", "Visible value formatting.")], "Uses native meter semantics rather than progress. Text repeats the meaningful unit and value."),
  d("Skeleton", "Status", "status/Feedback.tsx", "A restrained placeholder that retains a readable loading announcement.", '  return <Skeleton lines={4} label="Loading release notes" />;', [p("lines", "number", "One to twenty placeholder rows.", "3"), p("label", "string", "Loading announcement.", '"Loading content"')], "One labelled status region; placeholder shapes are hidden from readers. Reduced motion disables the pulse."),
  d("EmptyState", "Status", "status/Feedback.tsx", "A useful absence: explain what belongs here and give the next action.", '  return <EmptyState title="No releases yet" action={<Button size="sm">Create a release</Button>}>Your first release starts with a finished piece.</EmptyState>;', [p("title", "string", "Empty-state heading."), p("children", "ReactNode", "Reason or instructions."), p("action / icon", "ReactNode", "Optional action and decorative illustration.")], "A real heading and plain content; action retains its native semantics. Empty state does not steal focus.", undefined, "EmptyState, Button"),
  d("ErrorState", "Status", "status/Feedback.tsx", "A failure surface that names the problem and lets the user try again.", '  const [retried, setRetried] = useState(false);\n  return retried ? <p>Retry requested.</p> : <ErrorState title="Could not load artwork" onRetry={() => setRetried(true)}>Check your connection and try again.</ErrorState>;', [p("title", "string", "Specific problem heading."), p("onRetry", "() => void", "Requests a retry; own the data state outside the component.")], "Error content is announced. Retry is a native button and does not clear unrelated content."),
  d("ConnectionStatus", "Status", "status/Feedback.tsx", "A connection hint that follows actual browser online and offline events.", '  return <ConnectionStatus />;', [p("onlineLabel / offlineLabel", "string", "Customize the browser connectivity hints.")], "A live text status with stable server rendering. navigator.onLine is a connectivity hint, not proof your API is reachable.", "No continuous animation or polling."),
  d("SaveIndicator", "Status", "status/Feedback.tsx", "Keep the difference between saved, dirty, saving and failed visible.", '  const [state, setState] = useState<"saved" | "unsaved" | "saving" | "error">("unsaved");\n  return <><SaveIndicator state={state} onRetry={() => setState("saving")} /><select aria-label="Demo save state" value={state} onChange={e => setState(e.target.value as typeof state)}>{["saved","unsaved","saving","error"].map(v => <option key={v}>{v}</option>)}</select></>;', [p("state", '"saved" | "unsaved" | "saving" | "error"', "Actual persistence state supplied by your app."), p("onRetry", "() => void", "Optional retry for a failed save.")], "Changes are announced politely. The retry control appears only when it can recover a failure."),
  d("AsyncBoundary", "Status", "status/Feedback.tsx", "One readable contract for ready, loading, empty and failed content.", '  const [state, setState] = useState<"ready" | "loading" | "empty" | "error">("ready");\n  return <><select aria-label="Demo content state" value={state} onChange={e => setState(e.target.value as typeof state)}>{["ready","loading","empty","error"].map(v => <option key={v}>{v}</option>)}</select><AsyncBoundary state={state} onRetry={() => setState("ready")}><p>The archive is ready.</p></AsyncBoundary></>;', [p("state", '"loading" | "empty" | "error" | "ready"', "External async state."), p("loading / empty", "ReactNode", "Optional state-specific surfaces."), p("error / onRetry", "string / function", "Failure explanation and recovery.")], "Default placeholders are labelled; error recovery is keyboard accessible. It does not fetch or infer emptiness."),
  d("TaskProgress", "Status", "status/Feedback.tsx", "Make a multi-stage operation legible, including partial completion and failure.", '  const [cancelled, setCancelled] = useState(false);\n  return <TaskProgress label="Prepare release" onCancel={() => setCancelled(true)} steps={[{id:"a",label:"Validate",state:"complete"},{id:"b",label:"Build",state:cancelled ? "error" : "running",detail:cancelled ? "Cancelled by you" : "Compiling package"},{id:"c",label:"Publish",state:"queued"}]} />;', [p("steps", "TaskStep[]", "Stable id, label, state and optional detail."), p("onCancel", "() => void", "Shown while a step is running. Consumer cancels the real task.")], "Ordered steps expose readable states. Progress counts completed steps; error text does not rely on color."),
  d("AsyncButton", "Status", "status/AsyncButton.tsx", "An action whose feedback follows the real promise, with duplicate clicks prevented.", '  return <AsyncButton action={() => navigator.clipboard.writeText("Mizu")} successLabel="Copied">Copy Mizu</AsyncButton>;', [p("action", "(signal: AbortSignal) => Promise<unknown>", "Actual action. Signal aborts on unmount."), p("successLabel", "string", "Completed action name.", '"Done"'), p("onError", "(error: unknown) => void", "Optional error reporting.")], "Pending retains the action label and disables repeat clicks. Errors are announced; a retry starts a fresh action.", "Promise-driven state; no simulated delay."),
];
